CREATE TABLE tasks (
    id INT PRIMARY KEY,
    task VARCHAR(255) NOT NULL,
    note VARCHAR(255),
    done_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);